# Generated by Django 4.2.10 on 2024-05-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='os',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='computerlaptop',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.os'),
        ),
    ]
