# Generated by Django 4.2.10 on 2024-06-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='object',
            field=models.CharField(choices=[('host', 'Host'), ('frontend', 'Front'), ('at', 'AT'), ('backend', 'Backend'), ('hardware', 'Hardware'), ('database', 'DataBase'), ('user', 'User'), ('os', 'Os')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='subject',
            field=models.CharField(choices=[('host', 'Host'), ('frontend', 'Front'), ('at', 'AT'), ('backend', 'Backend'), ('hardware', 'Hardware'), ('database', 'DataBase'), ('user', 'User'), ('os', 'Os')], max_length=50),
        ),
    ]
