# Generated by Django 4.2.10 on 2024-06-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userpermission_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='object',
            field=models.CharField(choices=[('database', 'DataBase'), ('user', 'User'), ('at', 'AT'), ('frontend', 'Front'), ('hardware', 'Hardware'), ('host', 'Host'), ('backend', 'Backend'), ('os', 'Os')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='subject',
            field=models.CharField(choices=[('database', 'DataBase'), ('user', 'User'), ('at', 'AT'), ('frontend', 'Front'), ('hardware', 'Hardware'), ('host', 'Host'), ('backend', 'Backend'), ('os', 'Os')], max_length=50),
        ),
    ]
