# Generated by Django 4.2.10 on 2024-05-14 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_os_comment_os_version_alter_computerlaptop_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis_file', models.FileField(upload_to='basis_files/')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_bases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.basis')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.computerlaptop')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.permissiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=100)),
                ('server_role', models.CharField(max_length=255)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.os')),
                ('responsible_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.os')),
            ],
        ),
    ]
