# Generated by Django 4.2.10 on 2024-05-16 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_basis_permissiontype_userpermission_server_atm'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='responsible_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department'),
        ),
    ]
