# Generated by Django 4.2.10 on 2024-07-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_userpermission_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='object',
            field=models.CharField(choices=[('backend', 'Backend'), ('os', 'Os'), ('user', 'User'), ('frontend', 'Front'), ('database', 'DataBase'), ('host', 'Host'), ('at', 'AT'), ('hardware', 'Hardware')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='subject',
            field=models.CharField(choices=[('backend', 'Backend'), ('os', 'Os'), ('user', 'User'), ('frontend', 'Front'), ('database', 'DataBase'), ('host', 'Host'), ('at', 'AT'), ('hardware', 'Hardware')], max_length=50),
        ),
    ]
