# Generated by Django 4.2.10 on 2024-05-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_server_responsible_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='basis',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
