# Generated by Django 4.2.10 on 2024-05-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_service_socket_appservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appservice',
            name='service_type',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
