# Generated by Django 4.2.10 on 2024-07-18 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_asset_remove_userpermission_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.asset'),
        ),
        migrations.AlterField(
            model_name='backend',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.asset'),
        ),
        migrations.AlterField(
            model_name='database',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.asset'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.asset'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.asset'),
        ),
        migrations.AlterField(
            model_name='service',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.asset'),
        ),
    ]
