# Generated by Django 4.2.10 on 2024-07-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_atm_asset_alter_backend_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='inventor_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
