# Generated by Django 4.2.10 on 2024-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_socket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerlaptop',
            name='mac_address',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
