# Generated by Django 4.2.10 on 2024-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_computerlaptop_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerlaptop',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
