# Generated by Django 4.2.10 on 2024-07-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_hardware_inventor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='inventor_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
