# Generated by Django 4.2.10 on 2024-05-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_computerlaptop_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='basis',
            name='reg_number',
            field=models.CharField(default='12-06/344', max_length=100),
            preserve_default=False,
        ),
    ]
