# Generated by Django 4.2.10 on 2024-05-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_basis_reg_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basis',
            name='title',
            field=models.CharField(blank=True, default='bla bla', max_length=255),
            preserve_default=False,
        ),
    ]
