# Generated by Django 4.0.6 on 2024-07-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_userpermission_basis_given_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='backend',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='database',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='service',
            name='asset',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
