# Generated by Django 4.2.10 on 2024-05-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_basis_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='permission',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.ManyToManyField(related_name='given_permissions', to='myapp.permissiontype'),
        ),
    ]
