# Generated by Django 4.2.10 on 2024-08-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_atm_asset_remove_backend_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='myapp.subnet')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='ips',
            field=models.ManyToManyField(to='myapp.ipaddress'),
        ),
    ]
