# Generated by Django 4.2.10 on 2024-05-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_userpermission_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissiontype',
            old_name='permission_name',
            new_name='name',
        ),
    ]
