# Generated by Django 4.2.10 on 2024-05-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_permission_name_permissiontype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpermission',
            old_name='permission',
            new_name='permissions',
        ),
    ]
