# Generated by Django 4.2.10 on 2024-05-17 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_userpermission_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='basis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.basis'),
            preserve_default=False,
        ),
    ]
