# Generated by Django 4.2.10 on 2024-05-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_userpermission_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.computerlaptop'),
        ),
    ]
