# Generated by Django 4.2.10 on 2024-05-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_userpermission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basis',
            name='reg_number',
        ),
    ]
