# Generated by Django 4.2.10 on 2024-05-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_basis_reg_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='permissions',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.permissiontype'),
        ),
    ]
