# Generated by Django 4.2.10 on 2024-05-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_userpermission_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basis',
            name='reg_number',
            field=models.CharField(default='32-23', max_length=100),
            preserve_default=False,
        ),
    ]
