# Generated by Django 4.2.10 on 2024-05-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_basis_reg_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerlaptop',
            name='specifications',
            field=models.TextField(null=True),
        ),
    ]
