# Generated by Django 4.2.10 on 2024-06-20 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0026_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('db_model', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inventor_number', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('manager', models.CharField(max_length=255)),
                ('manager_ip', models.CharField(max_length=255)),
                ('responsible_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department')),
                ('responsible_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_hardware', to='myapp.hardware')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_os', to='myapp.os')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='computerlaptop',
            name='os',
        ),
        migrations.RemoveField(
            model_name='computerlaptop',
            name='responsible_employee',
        ),
        migrations.RemoveField(
            model_name='server',
            name='os',
        ),
        migrations.RemoveField(
            model_name='server',
            name='responsible_department',
        ),
        migrations.RemoveField(
            model_name='server',
            name='responsible_employee',
        ),
        migrations.RenameField(
            model_name='userpermission',
            old_name='user',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='basis',
            name='given_by',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='device',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='basis_given_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bases_given_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpermission',
            name='expire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpermission',
            name='given_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basis',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='AppService',
        ),
        migrations.DeleteModel(
            name='ComputerLaptop',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='Socket',
        ),
        migrations.AddField(
            model_name='frontend',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='front_host', to='myapp.host'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='soft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='front_soft_service', to='myapp.service'),
        ),
        migrations.AddField(
            model_name='database',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_host', to='myapp.host'),
        ),
        migrations.AddField(
            model_name='database',
            name='soft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_soft_service', to='myapp.service'),
        ),
        migrations.AddField(
            model_name='backend',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_host', to='myapp.host'),
        ),
        migrations.AddField(
            model_name='backend',
            name='soft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_service_soft', to='myapp.service'),
        ),
        migrations.AddField(
            model_name='at',
            name='backend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_back', to='myapp.backend'),
        ),
        migrations.AddField(
            model_name='at',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_database', to='myapp.database'),
        ),
        migrations.AddField(
            model_name='at',
            name='frontend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_frontend', to='myapp.frontend'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.hardware'),
        ),
    ]
